PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

CREATE TABLE CONF (
    ITEM  TEXT    PRIMARY KEY
                  UNIQUE
                  NOT NULL,
    VALUE BOOLEAN
);

CREATE TABLE DATAMODEL (
    DM_NAME TEXT PRIMARY KEY
               COLLATE NOCASE
               NOT NULL
               UNIQUE ON CONFLICT IGNORE
);

CREATE TABLE DISRUPTORS (
    DM_NAME   TEXT REFERENCES DATAMODEL (DM_NAME),
    TYPE      TEXT,
    NAME      TEXT,
    STATEFUL  BOOLEAN,
    PRIMARY KEY (
        DM_NAME,
        NAME
    ) ON CONFLICT IGNORE
);

CREATE TABLE DATA (
    ID        INTEGER  PRIMARY KEY ASC AUTOINCREMENT,
    TYPE      TEXT,
    DM_NAME   TEXT REFERENCES DATAMODEL (DM_NAME),
    CONTENTS  BLOB,
    SIZE      INTEGER,
    SENT_DATE DATETIME,
    ACK_DATE  DATETIME
);

CREATE TABLE STEPS (
    DATA_ID   INTEGER REFERENCES DATA (ID),
    STEP_ID   INTEGER,
    DISRUPTOR_NAME         REFERENCES DISRUPTORS (NAME),
    GEN_ARGS  TEXT,
    SPE_ARGS  TEXT,
    PRIMARY KEY (
        DATA_ID,
        STEP_ID
    )
);

CREATE TABLE FEEDBACK (
    DATA_ID  INTEGER REFERENCES DATA (ID),
    FBK_ID   INTEGER,
    SRC      TEXT,
    CONTENTS BLOB,
    PRIMARY KEY (
        DATA_ID,
        FBK_ID
    )
);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
