PRAGMA foreign_keys = off;
BEGIN TRANSACTION;

CREATE TABLE STEPS (
    DATA_ID   INTEGER REFERENCES DATA (DATA_ID),
    STEP_ID   INTEGER,
    DMAKER_ID         REFERENCES DMAKERS (DMAKER_ID),
    GEN_ARGS  TEXT,
    SPE_ARGS  TEXT,
    PRIMARY KEY (
        DATA_ID ASC,
        STEP_ID
    )
);

CREATE TABLE DMAKERS (
    DMAKER_ID INTEGER PRIMARY KEY
                      UNIQUE,
    NAME      TEXT,
    DISRUPTOR BOOLEAN,
    STATEFUL  BOOLEAN
);

CREATE TABLE FEEDBACK (
    DATA_ID  INTEGER REFERENCES DATA (DATA_ID),
    FBK_ID   INTEGER,
    SRC      TEXT,
    CONTENTS BLOB,
    PRIMARY KEY (
        DATA_ID ASC,
        FBK_ID
    )
);

CREATE TABLE DATA (
    DATA_ID   INTEGER  PRIMARY KEY ASC AUTOINCREMENT,
    CONTENTS  BLOB,
    SIZE      INTEGER,
    SENT_DATE DATETIME,
    ACK_DATE  DATETIME
);

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
